### ISSUE TITLE
read cfg file error

### ISSUE THREAD

**Issue by varrella** [TUMFTM/CameraRadarFusionNet#17]
in utils/config.py ,line 58:
commit = str(subprocess.check_output(["git", "rev-parse", "HEAD"]), 'utf-8').strip()
branch = str(subprocess.check_output(["git", "rev-parse", "--abbrev-ref", "HEAD"]).strip(), 'utf-8').strip()

error like this :
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Traceback (most recent call last):
  File "test_crfnet.py", line 117, in <module>
    cfg = get_config(args.config)
  File "../crfnet/utils/config.py", line 59, in get_config
    commit = str(subprocess.check_output(["git", "rev-parse", "HEAD"]), 'utf-8').strip()
  File "/home/ZT/anaconda3/envs/Keras-Tensorflow/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/home/ZT/anaconda3/envs/Keras-Tensorflow/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 128.

**Comment by ta984ia** [comment]
I am facing the same issue. Did you find the solution ?

**Comment by varrella** [comment]
I found these two lines are probably used to configure 'Git' (but I don't really understand the details)，so I comment these two lines. like this，and then it can run with no error:





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TUMFTM/CameraRadarFusionNet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月17日(星期三) 晚上8:47
收件人:&nbsp;"TUMFTM/CameraRadarFusionNet"<CameraRadarFusionNet@noreply.github.com&gt;;
抄送:&nbsp;"ZT"<1195164939@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [TUMFTM/CameraRadarFusionNet] read cfg file error (#17)





 
I am facing the same issue. Did you find the solution ?

**Comment by ta984ia** [comment]
Thankyou, I was able to solve the git issue by commenting those lines.
