### ISSUE TITLE
No such layer: block1_conv1

### ISSUE THREAD

**Issue by varrella** [TUMFTM/CameraRadarFusionNet#29]
when I change the value of "network" in default.cfg file, I got the following question, how to solve it?
It seems like the code works well when the value of "network" is "vgg16" or "vgg19", but when I modify the value of "network" to "densnet121" or "resnet152", the following problem will occur, how to solve it?

Traceback (most recent call last):
  File "train_crfnet.py", line 431, in <module>
    main()
  File "train_crfnet.py", line 326, in main
    model, training_model, prediction_model = create_models(
  File "train_crfnet.py", line 145, in create_models
    model          = model_with_weights(backbone_retinanet(num_classes, num_anchors=num_anchors, modifier=modifier, inputs=inputs, distance=distance, cfg=cfg), weights=weights, skip_mismatch=True, config=copy.deepcopy(cfg), num_classes=num_classes)
  File "train_crfnet.py", line 91, in model_with_weights
    model_weights = model.get_layer(layer_name).get_weights()
  File "/home/ZT/anaconda3/envs/crfnet-tf2/lib/python3.8/site-packages/keras/engine/network.py", line 358, in get_layer
    raise ValueError('No such layer: ' + name)
ValueError: No such layer: block1_conv1

fragment of default.cfg:
[CRF-Net]
channels = [0,1,2,5,18]
image_height = 360
image_width = 640

dropout_radar = 0.0
dropout_image = 0.2

network = densenet121
network_width = 1.0
pooling = max

anchor_params = small

**Comment by hershita07** [comment]
hey, did you get the solution to this?

**Comment by tejasri19** [comment]
@varrella @TUMFTM @fnobis  I ran into the same error as mentioned above while changing the "network" to "densnet121" or "resnet152" .   Help needed to resolve!
