### ISSUE TITLE
TypeError: from_file_multisweep() got an unexpected keyword argument 'merge'

### ISSUE THREAD

**Issue by KhaaQ** [TUMFTM/CameraRadarFusionNet#3]
Hi. i am using nuscense -mini for initially . But after two epoch giving the error. thankyou

============================================================
		##### Start Training #####
============================================================
Epoch 1/20
Epoch 1/20
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/khaula/.local/lib/python3.6/site-packages/keras/utils/data_utils.py", line 401, in get_index
    return _SHARED_SEQUENCES[uid][i]
  File "../crfnet/data_processing/generator/generator.py", line 361, in __getitem__
    inputs, targets = self.compute_input_output(group, inference=self.inference)
  File "../crfnet/data_processing/generator/nuscenes_generator.py", line 588, in compute_input_output
    inputs, targets = super(NuscenesGenerator, self).compute_input_output(group)
  File "../crfnet/data_processing/generator/generator.py", line 319, in compute_input_output
    image_group       = self.load_image_group(group)
  File "../crfnet/data_processing/generator/generator.py", line 190, in load_image_group
    return [self.load_image(image_index) for image_index in group]
  File "../crfnet/data_processing/generator/generator.py", line 190, in <listcomp>
    return [self.load_image(image_index) for image_index in group]
  File "../crfnet/data_processing/generator/nuscenes_generator.py", line 382, in load_image
    sensor_channel, nsweeps=required_sweep_count, min_distance=0.0, merge=False)
TypeError: from_file_multisweep() got an unexpected keyword argument 'merge'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train_crfnet.py", line 421, in <module>
    main()
  File "train_crfnet.py", line 385, in main
    class_weight=class_weights_labels
  File "/home/khaula/.local/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/khaula/.local/lib/python3.6/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/khaula/.local/lib/python3.6/site-packages/keras/engine/training_generator.py", line 181, in fit_generator
    generator_output = next(output_generator)
  File "/home/khaula/.local/lib/python3.6/site-packages/keras/utils/data_utils.py", line 601, in get
    six.reraise(*sys.exc_info())
  File "/home/khaula/.local/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/khaula/.local/lib/python3.6/site-packages/keras/utils/data_utils.py", line 595, in get
    inputs = self.queue.get(block=True).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
TypeError: from_file_multisweep() got an unexpected keyword argument 'merge'

**Comment by mgeisslinger** [comment]
Please make sure to use this fork of the nuscenes package here:
https://github.com/Fellfalla/nuscenes-devkit

**Comment by RRK13** [comment]
please share the key difference between the below 2 git, and why it's specific to CameraRadarFusionNet?
1. https://github.com/nutonomy/nuscenes-devkit.git
2. https://github.com/Fellfalla/nuscenes-devkit

**Comment by fnobis** [comment]
There are several differences, you can find in the history of the package. One major reason for the fork is the compability to python3.5.

**Comment by guiyuliu** [comment]
I use python3.5 and pip install the specific https://github.com/Fellfalla/nuscenes-devkit， I still get this error

**Comment by guiyuliu** [comment]
Requirement already satisfied: webencodings in /root/anaconda3/envs/crfnet1/lib/python3.5/site-packages (from bleach->nbconvert->jupyter->nuscenes-devkit@ git+https://github.com/Fellfalla/nuscenes-devkit.git@
master->crfnet==0.99.0) (0.5.1)
Requirement already satisfied: parso<0.8.0,>=0.7.0 in /root/anaconda3/envs/crfnet1/lib/python3.5/site-packages (from jedi>=0.10->ipython>=5.0.0->ipykernel->jupyter->nuscenes-devkit@ git+https://github.com/Fel
lfalla/nuscenes-devkit.git@master->crfnet==0.99.0) (0.7.0)
Requirement already satisfied: attrs>=17.4.0 in /root/anaconda3/envs/crfnet1/lib/python3.5/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->notebook->jupyter->nuscenes-devkit@ git+https://github.com/Fel
lfalla/nuscenes-devkit.git@master->crfnet==0.99.0) (19.3.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /root/anaconda3/envs/crfnet1/lib/python3.5/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->notebook->jupyter->nuscenes-devkit@ git+https://github.co
m/Fellfalla/nuscenes-devkit.git@master->crfnet==0.99.0) (0.16.0)
Installing collected packages: crfnet
  Attempting uninstall: crfnet
    Found existing installation: crfnet 0.99.0
    Uninstalling crfnet-0.99.0:
      Successfully uninstalled crfnet-0.99.0
  Running setup.py develop for crfnet
Successfully installed crfnet

I am very sure I installed all requirements

**Comment by guiyuliu** [comment]
> I use python3.5 and pip install the specific [https://github.com/Fellfalla/nuscenes-devkit，](https://github.com/Fellfalla/nuscenes-devkit%EF%BC%8C) I still get this error

problem solved ， I already installed nuscenes-devkit  from nutonomy and and add it to my PYTHONPATH
so my python found it before the env nuscenes-devkit

**Comment by paranh2o** [comment]
I got same error.  guiyuliu, how did you solve this problem?
